apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coit-frontend
  namespace: default
spec:
  template:
    metadata:
            annotations:
                    autoscaling.knative.dev/max-scale: "5"
                    autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m5s"
                    autoscaling.knative.dev/target: "50"
                    autoscaling.knative.dev/metric: "cpu"
                    autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"      
    spec:
      containers:
              - image: divyaren/myfirstrepo:v21
                env:
                  - name: COIT_BACKEND_URL
                    value: "http://coit-backend1.default.34.123.134.213.sslip.io"
